services:
  db:
    image: postgres:16
    container_name: monorepo_DB
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/Dockerfile.backend
    environment:
      DATABASE_URL: postgres://appuser:secret@db:5432/appdb
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./apps/backend:/app/apps/backend
      - ./packages:/app/packages
    command: sh -c "pnpm install && pnpm run dev"

  battlemap:
    container_name: battlemap
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        APP_NAME: battlemap
    ports:
      - 3001:3001
    volumes:
      - ./apps/battlemap:/app/apps/battlemap
      - ./packages:/app/packages
    command: sh -c "pnpm install && pnpm run dev"

  sessionplaner:
    container_name: sessionplaner
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        APP_NAME: sessionplaner
    ports:
      - 3002:3002
    volumes:
      - ./apps/sessionplaner:/app/apps/sessionplaner
      - ./packages:/app/packages
    command: sh -c "pnpm install && pnpm run dev"

  worldbuilder:
    container_name: worldbuilder
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        APP_NAME: worldbuilder
    ports:
      - 3003:3003
    volumes:
      - ./apps/worldbuilder:/app/apps/worldbuilder
      - ./packages:/app/packages
    command: sh -c "pnpm install && pnpm run dev"


volumes:
  pgdata:
  backend_node_modules:
  worldbuilder_node_modules: